version: '3.9'

services:
  api:
    container_name: sale1h-api
    build: ./sale1h-api
    volumes:
      - ./sale1h-api:/app
    command: npm run start
    networks:
      - common
    environment:
      PORT: 8902
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  web:
    container_name: sale1h-web
    build: ./sale1h-web
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - common
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - .data/redis:/data
    restart: unless-stopped
    networks:
      - common
  nginx:
    depends_on:
      - api
      - web
    restart: always
    build:
      dockerfile: dockerfile
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - common
networks:
  common: