FROM node:18-alpine3.15 as builder
WORKDIR /app
COPY ./package*.json ./
RUN npm i -f
COPY . .
RUN npm run build

FROM nginx
EXPOSE 8901
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html